[package]
name = "food-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# catppuccin-egui = { git = "https://github.com/catppuccin/egui", branch = "main" }
egui_extras = { version = "0.33.0", features = ["image", "http"] }
eframe = "0.33.0"
ehttp = "0.6.0"
image = { version = "0.25.1", default-features = false, features = ["jpeg"] }
poll-promise = "0.3"
recipe-scraper.workspace = true
ingredient.workspace = true
serde_json.workspace = true
egui_ltreeview = "0.6"
rand = "0.9.0"
tracing.workspace = true
tracing-wasm = "0.2.1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tracing-subscriber = "0.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"
console_error_panic_hook = "0.1"

[lints]
workspace = true
