[package]
name = "food-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version="4.5.4", features=["derive"]}
recipe-scraper-fetcher = {path = "../recipe-scraper-fetcher"}
tokio = { version = "1.47.1", features = ["full"] }
serde_json = "1.0"
ingredient= {path = "../ingredient-parser"}
atty = "0.2"

[lints]
workspace = true
