[package]
name = "food-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version="4.5.4", features=["derive"]}
recipe-scraper-fetcher = {path = "../recipe-scraper-fetcher"}
tokio = { workspace = true, features = ["full"] }
serde_json.workspace = true
ingredient.workspace = true

[lints]
workspace = true
